/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IEREBRUSMANAGER,
  IEREBRUSMANAGERInterface,
} from "../IEREBRUSMANAGER";

const _abi = [
  {
    inputs: [],
    name: "getPayoutAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isOperator",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IEREBRUSMANAGER__factory {
  static readonly abi = _abi;
  static createInterface(): IEREBRUSMANAGERInterface {
    return new utils.Interface(_abi) as IEREBRUSMANAGERInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEREBRUSMANAGER {
    return new Contract(address, _abi, signerOrProvider) as IEREBRUSMANAGER;
  }
}
