/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IEREBRUSREGISTRY,
  IEREBRUSREGISTRYInterface,
} from "../IEREBRUSREGISTRY";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nodeID",
        type: "uint256",
      },
    ],
    name: "getWifiDetails",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IEREBRUSREGISTRY__factory {
  static readonly abi = _abi;
  static createInterface(): IEREBRUSREGISTRYInterface {
    return new utils.Interface(_abi) as IEREBRUSREGISTRYInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEREBRUSREGISTRY {
    return new Contract(address, _abi, signerOrProvider) as IEREBRUSREGISTRY;
  }
}
